// Mocks generated by Mockito from annotations
// in ditonton_tv/test/presentation/pages/home_tv_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i7;

import 'package:bloc/bloc.dart' as _i8;
import 'package:ditonton_tv/domain/usecases/get_airing_today_tvs.dart' as _i2;
import 'package:ditonton_tv/domain/usecases/get_on_the_air_tvs.dart' as _i3;
import 'package:ditonton_tv/domain/usecases/get_popular_tvs.dart' as _i4;
import 'package:ditonton_tv/domain/usecases/get_top_rated_tvs.dart' as _i5;
import 'package:ditonton_tv/presentation/bloc/tv_list_bloc.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetAiringTodayTVs_0 extends _i1.SmartFake
    implements _i2.GetAiringTodayTVs {
  _FakeGetAiringTodayTVs_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetOnTheAirTVs_1 extends _i1.SmartFake
    implements _i3.GetOnTheAirTVs {
  _FakeGetOnTheAirTVs_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularTVs_2 extends _i1.SmartFake implements _i4.GetPopularTVs {
  _FakeGetPopularTVs_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedTVs_3 extends _i1.SmartFake
    implements _i5.GetTopRatedTVs {
  _FakeGetTopRatedTVs_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTVListState_4 extends _i1.SmartFake implements _i6.TVListState {
  _FakeTVListState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TVListBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVListBloc extends _i1.Mock implements _i6.TVListBloc {
  MockTVListBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetAiringTodayTVs get getAiringTodayTvs => (super.noSuchMethod(
    Invocation.getter(#getAiringTodayTvs),
    returnValue: _FakeGetAiringTodayTVs_0(
      this,
      Invocation.getter(#getAiringTodayTvs),
    ),
  ) as _i2.GetAiringTodayTVs);

  @override
  _i3.GetOnTheAirTVs get getOnTheAirTvs => (super.noSuchMethod(
    Invocation.getter(#getOnTheAirTvs),
    returnValue: _FakeGetOnTheAirTVs_1(
      this,
      Invocation.getter(#getOnTheAirTvs),
    ),
  ) as _i3.GetOnTheAirTVs);

  @override
  _i4.GetPopularTVs get getPopularTvs => (super.noSuchMethod(
    Invocation.getter(#getPopularTvs),
    returnValue: _FakeGetPopularTVs_2(this, Invocation.getter(#getPopularTvs)),
  ) as _i4.GetPopularTVs);

  @override
  _i5.GetTopRatedTVs get getTopRatedTvs => (super.noSuchMethod(
    Invocation.getter(#getTopRatedTvs),
    returnValue: _FakeGetTopRatedTVs_3(
      this,
      Invocation.getter(#getTopRatedTvs),
    ),
  ) as _i5.GetTopRatedTVs);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i6.TVListState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _FakeTVListState_4(this, Invocation.getter(#state)),
  ) as _i6.TVListState);

  @override
  _i7.Stream<_i6.TVListState> get stream => (super.noSuchMethod(
    Invocation.getter(#stream),
    returnValue: _i7.Stream<_i6.TVListState>.empty(),
  ) as _i7.Stream<_i6.TVListState>);

  @override
  void add(_i6.TVListEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i6.TVListEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i6.TVListState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i6.TVListEvent>(
    _i8.EventHandler<E, _i6.TVListState>? handler, {
    _i8.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i8.Transition<_i6.TVListEvent, _i6.TVListState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i6.TVListEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
    Invocation.method(#close, []),
    returnValue: _i7.Future<void>.value(),
    returnValueForMissingStub: _i7.Future<void>.value(),
  ) as _i7.Future<void>);

  @override
  void onChange(_i8.Change<_i6.TVListState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
