// Mocks generated by Mockito from annotations
// in ditonton_tv/test/presentation/pages/list_pages_nonempty_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i10;

import 'package:bloc/bloc.dart' as _i11;
import 'package:ditonton_tv/domain/usecases/get_airing_today_tvs.dart' as _i6;
import 'package:ditonton_tv/domain/usecases/get_on_the_air_tvs.dart' as _i8;
import 'package:ditonton_tv/domain/usecases/get_popular_tvs.dart' as _i2;
import 'package:ditonton_tv/domain/usecases/get_top_rated_tvs.dart' as _i4;
import 'package:ditonton_tv/presentation/bloc/airing_today_tvs_bloc.dart'
    as _i7;
import 'package:ditonton_tv/presentation/bloc/on_the_air_tvs_bloc.dart' as _i9;
import 'package:ditonton_tv/presentation/bloc/popular_tvs_bloc.dart' as _i3;
import 'package:ditonton_tv/presentation/bloc/top_rated_tvs_bloc.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetPopularTVs_0 extends _i1.SmartFake implements _i2.GetPopularTVs {
  _FakeGetPopularTVs_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePopularTVsState_1 extends _i1.SmartFake
    implements _i3.PopularTVsState {
  _FakePopularTVsState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedTVs_2 extends _i1.SmartFake
    implements _i4.GetTopRatedTVs {
  _FakeGetTopRatedTVs_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTopRatedTVsState_3 extends _i1.SmartFake
    implements _i5.TopRatedTVsState {
  _FakeTopRatedTVsState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAiringTodayTVs_4 extends _i1.SmartFake
    implements _i6.GetAiringTodayTVs {
  _FakeGetAiringTodayTVs_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAiringTodayTVsState_5 extends _i1.SmartFake
    implements _i7.AiringTodayTVsState {
  _FakeAiringTodayTVsState_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetOnTheAirTVs_6 extends _i1.SmartFake
    implements _i8.GetOnTheAirTVs {
  _FakeGetOnTheAirTVs_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOnTheAirTVsState_7 extends _i1.SmartFake
    implements _i9.OnTheAirTVsState {
  _FakeOnTheAirTVsState_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PopularTVsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularTVsBloc extends _i1.Mock implements _i3.PopularTVsBloc {
  MockPopularTVsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetPopularTVs get getPopularTvs => (super.noSuchMethod(
    Invocation.getter(#getPopularTvs),
    returnValue: _FakeGetPopularTVs_0(this, Invocation.getter(#getPopularTvs)),
  ) as _i2.GetPopularTVs);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i3.PopularTVsState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _FakePopularTVsState_1(this, Invocation.getter(#state)),
  ) as _i3.PopularTVsState);

  @override
  _i10.Stream<_i3.PopularTVsState> get stream => (super.noSuchMethod(
    Invocation.getter(#stream),
    returnValue: _i10.Stream<_i3.PopularTVsState>.empty(),
  ) as _i10.Stream<_i3.PopularTVsState>);

  @override
  void add(_i3.PopularTVsEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.PopularTVsEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.PopularTVsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.PopularTVsEvent>(
    _i11.EventHandler<E, _i3.PopularTVsState>? handler, {
    _i11.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i11.Transition<_i3.PopularTVsEvent, _i3.PopularTVsState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i3.PopularTVsEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> close() => (super.noSuchMethod(
    Invocation.method(#close, []),
    returnValue: _i10.Future<void>.value(),
    returnValueForMissingStub: _i10.Future<void>.value(),
  ) as _i10.Future<void>);

  @override
  void onChange(_i11.Change<_i3.PopularTVsState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TopRatedTVsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTVsBloc extends _i1.Mock implements _i5.TopRatedTVsBloc {
  MockTopRatedTVsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GetTopRatedTVs get getTopRatedTvs => (super.noSuchMethod(
    Invocation.getter(#getTopRatedTvs),
    returnValue: _FakeGetTopRatedTVs_2(
      this,
      Invocation.getter(#getTopRatedTvs),
    ),
  ) as _i4.GetTopRatedTVs);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i5.TopRatedTVsState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _FakeTopRatedTVsState_3(this, Invocation.getter(#state)),
  ) as _i5.TopRatedTVsState);

  @override
  _i10.Stream<_i5.TopRatedTVsState> get stream => (super.noSuchMethod(
    Invocation.getter(#stream),
    returnValue: _i10.Stream<_i5.TopRatedTVsState>.empty(),
  ) as _i10.Stream<_i5.TopRatedTVsState>);

  @override
  void add(_i5.TopRatedTVsEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i5.TopRatedTVsEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.TopRatedTVsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i5.TopRatedTVsEvent>(
    _i11.EventHandler<E, _i5.TopRatedTVsState>? handler, {
    _i11.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i11.Transition<_i5.TopRatedTVsEvent, _i5.TopRatedTVsState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i5.TopRatedTVsEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> close() => (super.noSuchMethod(
    Invocation.method(#close, []),
    returnValue: _i10.Future<void>.value(),
    returnValueForMissingStub: _i10.Future<void>.value(),
  ) as _i10.Future<void>);

  @override
  void onChange(_i11.Change<_i5.TopRatedTVsState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AiringTodayTVsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiringTodayTVsBloc extends _i1.Mock
    implements _i7.AiringTodayTVsBloc {
  MockAiringTodayTVsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GetAiringTodayTVs get getAiringTodayTvs => (super.noSuchMethod(
    Invocation.getter(#getAiringTodayTvs),
    returnValue: _FakeGetAiringTodayTVs_4(
      this,
      Invocation.getter(#getAiringTodayTvs),
    ),
  ) as _i6.GetAiringTodayTVs);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i7.AiringTodayTVsState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _FakeAiringTodayTVsState_5(this, Invocation.getter(#state)),
  ) as _i7.AiringTodayTVsState);

  @override
  _i10.Stream<_i7.AiringTodayTVsState> get stream => (super.noSuchMethod(
    Invocation.getter(#stream),
    returnValue: _i10.Stream<_i7.AiringTodayTVsState>.empty(),
  ) as _i10.Stream<_i7.AiringTodayTVsState>);

  @override
  void add(_i7.AiringTodayTVsEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i7.AiringTodayTVsEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i7.AiringTodayTVsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i7.AiringTodayTVsEvent>(
    _i11.EventHandler<E, _i7.AiringTodayTVsState>? handler, {
    _i11.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i11.Transition<_i7.AiringTodayTVsEvent, _i7.AiringTodayTVsState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i7.AiringTodayTVsEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> close() => (super.noSuchMethod(
    Invocation.method(#close, []),
    returnValue: _i10.Future<void>.value(),
    returnValueForMissingStub: _i10.Future<void>.value(),
  ) as _i10.Future<void>);

  @override
  void onChange(_i11.Change<_i7.AiringTodayTVsState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OnTheAirTVsBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnTheAirTVsBloc extends _i1.Mock implements _i9.OnTheAirTVsBloc {
  MockOnTheAirTVsBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.GetOnTheAirTVs get getOnTheAirTvs => (super.noSuchMethod(
    Invocation.getter(#getOnTheAirTvs),
    returnValue: _FakeGetOnTheAirTVs_6(
      this,
      Invocation.getter(#getOnTheAirTvs),
    ),
  ) as _i8.GetOnTheAirTVs);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i9.OnTheAirTVsState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _FakeOnTheAirTVsState_7(this, Invocation.getter(#state)),
  ) as _i9.OnTheAirTVsState);

  @override
  _i10.Stream<_i9.OnTheAirTVsState> get stream => (super.noSuchMethod(
    Invocation.getter(#stream),
    returnValue: _i10.Stream<_i9.OnTheAirTVsState>.empty(),
  ) as _i10.Stream<_i9.OnTheAirTVsState>);

  @override
  void add(_i9.OnTheAirTVsEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i9.OnTheAirTVsEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i9.OnTheAirTVsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i9.OnTheAirTVsEvent>(
    _i11.EventHandler<E, _i9.OnTheAirTVsState>? handler, {
    _i11.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i11.Transition<_i9.OnTheAirTVsEvent, _i9.OnTheAirTVsState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i9.OnTheAirTVsEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> close() => (super.noSuchMethod(
    Invocation.method(#close, []),
    returnValue: _i10.Future<void>.value(),
    returnValueForMissingStub: _i10.Future<void>.value(),
  ) as _i10.Future<void>);

  @override
  void onChange(_i11.Change<_i9.OnTheAirTVsState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
