// Mocks generated by Mockito from annotations
// in ditonton_tv/test/presentation/pages/tv_season_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i9;

import 'package:bloc/bloc.dart' as _i10;
import 'package:ditonton_tv/domain/usecases/get_season_detail.dart' as _i4;
import 'package:ditonton_tv/domain/usecases/get_tv_detail.dart' as _i2;
import 'package:ditonton_tv/domain/usecases/get_tv_recommendations.dart' as _i3;
import 'package:ditonton_tv/domain/usecases/get_watchlist_tv_status.dart'
    as _i5;
import 'package:ditonton_tv/domain/usecases/remove_watchlist_tv.dart' as _i7;
import 'package:ditonton_tv/domain/usecases/save_watchlist_tv.dart' as _i6;
import 'package:ditonton_tv/presentation/bloc/tv_detail_bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetTVDetail_0 extends _i1.SmartFake implements _i2.GetTVDetail {
  _FakeGetTVDetail_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTVRecommendations_1 extends _i1.SmartFake
    implements _i3.GetTVRecommendations {
  _FakeGetTVRecommendations_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetSeasonDetail_2 extends _i1.SmartFake
    implements _i4.GetSeasonDetail {
  _FakeGetSeasonDetail_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchlistTVStatus_3 extends _i1.SmartFake
    implements _i5.GetWatchlistTVStatus {
  _FakeGetWatchlistTVStatus_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlistTV_4 extends _i1.SmartFake
    implements _i6.SaveWatchlistTV {
  _FakeSaveWatchlistTV_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlistTV_5 extends _i1.SmartFake
    implements _i7.RemoveWatchlistTV {
  _FakeRemoveWatchlistTV_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTVDetailState_6 extends _i1.SmartFake implements _i8.TVDetailState {
  _FakeTVDetailState_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TVDetailBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVDetailBloc extends _i1.Mock implements _i8.TVDetailBloc {
  MockTVDetailBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTVDetail get getTvDetail => (super.noSuchMethod(
    Invocation.getter(#getTvDetail),
    returnValue: _FakeGetTVDetail_0(this, Invocation.getter(#getTvDetail)),
  ) as _i2.GetTVDetail);

  @override
  _i3.GetTVRecommendations get getTvRecommendations => (super.noSuchMethod(
    Invocation.getter(#getTvRecommendations),
    returnValue: _FakeGetTVRecommendations_1(
      this,
      Invocation.getter(#getTvRecommendations),
    ),
  ) as _i3.GetTVRecommendations);

  @override
  _i4.GetSeasonDetail get getSeasonDetail => (super.noSuchMethod(
    Invocation.getter(#getSeasonDetail),
    returnValue: _FakeGetSeasonDetail_2(
      this,
      Invocation.getter(#getSeasonDetail),
    ),
  ) as _i4.GetSeasonDetail);

  @override
  _i5.GetWatchlistTVStatus get getWatchlistTvStatus => (super.noSuchMethod(
    Invocation.getter(#getWatchlistTvStatus),
    returnValue: _FakeGetWatchlistTVStatus_3(
      this,
      Invocation.getter(#getWatchlistTvStatus),
    ),
  ) as _i5.GetWatchlistTVStatus);

  @override
  _i6.SaveWatchlistTV get saveWatchlistTv => (super.noSuchMethod(
    Invocation.getter(#saveWatchlistTv),
    returnValue: _FakeSaveWatchlistTV_4(
      this,
      Invocation.getter(#saveWatchlistTv),
    ),
  ) as _i6.SaveWatchlistTV);

  @override
  _i7.RemoveWatchlistTV get removeWatchlistTv => (super.noSuchMethod(
    Invocation.getter(#removeWatchlistTv),
    returnValue: _FakeRemoveWatchlistTV_5(
      this,
      Invocation.getter(#removeWatchlistTv),
    ),
  ) as _i7.RemoveWatchlistTV);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i8.TVDetailState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _FakeTVDetailState_6(this, Invocation.getter(#state)),
  ) as _i8.TVDetailState);

  @override
  _i9.Stream<_i8.TVDetailState> get stream => (super.noSuchMethod(
    Invocation.getter(#stream),
    returnValue: _i9.Stream<_i8.TVDetailState>.empty(),
  ) as _i9.Stream<_i8.TVDetailState>);

  @override
  void add(_i8.TVDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i8.TVDetailEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i8.TVDetailState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i8.TVDetailEvent>(
    _i10.EventHandler<E, _i8.TVDetailState>? handler, {
    _i10.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i10.Transition<_i8.TVDetailEvent, _i8.TVDetailState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i8.TVDetailEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> close() => (super.noSuchMethod(
    Invocation.method(#close, []),
    returnValue: _i9.Future<void>.value(),
    returnValueForMissingStub: _i9.Future<void>.value(),
  ) as _i9.Future<void>);

  @override
  void onChange(_i10.Change<_i8.TVDetailState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
