// Mocks generated by Mockito from annotations
// in ditonton_movie/test/presentation/pages/list_pages_nonempty_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i6;

import 'package:bloc/bloc.dart' as _i7;
import 'package:ditonton_movie/domain/usecases/get_popular_movies.dart' as _i2;
import 'package:ditonton_movie/domain/usecases/get_top_rated_movies.dart'
    as _i4;
import 'package:ditonton_movie/presentation/bloc/popular_movies_bloc.dart'
    as _i3;
import 'package:ditonton_movie/presentation/bloc/top_rated_movies_bloc.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetPopularMovies_0 extends _i1.SmartFake
    implements _i2.GetPopularMovies {
  _FakeGetPopularMovies_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePopularMoviesState_1 extends _i1.SmartFake
    implements _i3.PopularMoviesState {
  _FakePopularMoviesState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedMovies_2 extends _i1.SmartFake
    implements _i4.GetTopRatedMovies {
  _FakeGetTopRatedMovies_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTopRatedMoviesState_3 extends _i1.SmartFake
    implements _i5.TopRatedMoviesState {
  _FakeTopRatedMoviesState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PopularMoviesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularMoviesBloc extends _i1.Mock implements _i3.PopularMoviesBloc {
  MockPopularMoviesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetPopularMovies get getPopularMovies => (super.noSuchMethod(
    Invocation.getter(#getPopularMovies),
    returnValue: _FakeGetPopularMovies_0(
      this,
      Invocation.getter(#getPopularMovies),
    ),
  ) as _i2.GetPopularMovies);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i3.PopularMoviesState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _FakePopularMoviesState_1(this, Invocation.getter(#state)),
  ) as _i3.PopularMoviesState);

  @override
  _i6.Stream<_i3.PopularMoviesState> get stream => (super.noSuchMethod(
    Invocation.getter(#stream),
    returnValue: _i6.Stream<_i3.PopularMoviesState>.empty(),
  ) as _i6.Stream<_i3.PopularMoviesState>);

  @override
  void add(_i3.PopularMoviesEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i3.PopularMoviesEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.PopularMoviesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i3.PopularMoviesEvent>(
    _i7.EventHandler<E, _i3.PopularMoviesState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i7.Transition<_i3.PopularMoviesEvent, _i3.PopularMoviesState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i3.PopularMoviesEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
    Invocation.method(#close, []),
    returnValue: _i6.Future<void>.value(),
    returnValueForMissingStub: _i6.Future<void>.value(),
  ) as _i6.Future<void>);

  @override
  void onChange(_i7.Change<_i3.PopularMoviesState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TopRatedMoviesBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedMoviesBloc extends _i1.Mock
    implements _i5.TopRatedMoviesBloc {
  MockTopRatedMoviesBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GetTopRatedMovies get getTopRatedMovies => (super.noSuchMethod(
    Invocation.getter(#getTopRatedMovies),
    returnValue: _FakeGetTopRatedMovies_2(
      this,
      Invocation.getter(#getTopRatedMovies),
    ),
  ) as _i4.GetTopRatedMovies);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i5.TopRatedMoviesState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _FakeTopRatedMoviesState_3(this, Invocation.getter(#state)),
  ) as _i5.TopRatedMoviesState);

  @override
  _i6.Stream<_i5.TopRatedMoviesState> get stream => (super.noSuchMethod(
    Invocation.getter(#stream),
    returnValue: _i6.Stream<_i5.TopRatedMoviesState>.empty(),
  ) as _i6.Stream<_i5.TopRatedMoviesState>);

  @override
  void add(_i5.TopRatedMoviesEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i5.TopRatedMoviesEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.TopRatedMoviesState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i5.TopRatedMoviesEvent>(
    _i7.EventHandler<E, _i5.TopRatedMoviesState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i7.Transition<_i5.TopRatedMoviesEvent, _i5.TopRatedMoviesState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i5.TopRatedMoviesEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
    Invocation.method(#close, []),
    returnValue: _i6.Future<void>.value(),
    returnValueForMissingStub: _i6.Future<void>.value(),
  ) as _i6.Future<void>);

  @override
  void onChange(_i7.Change<_i5.TopRatedMoviesState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
