// Mocks generated by Mockito from annotations
// in ditonton/test/presentation/pages/home_movie_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i15;
import 'dart:ui' as _i16;

import 'package:ditonton/common/state_enum.dart' as _i13;
import 'package:ditonton/domain/entities/movie.dart' as _i12;
import 'package:ditonton/domain/entities/tv.dart' as _i18;
import 'package:ditonton/domain/usecases/get_airing_today_tvs.dart' as _i5;
import 'package:ditonton/domain/usecases/get_now_playing_movies.dart' as _i2;
import 'package:ditonton/domain/usecases/get_on_the_air_tvs.dart' as _i6;
import 'package:ditonton/domain/usecases/get_popular_movies.dart' as _i3;
import 'package:ditonton/domain/usecases/get_popular_tvs.dart' as _i7;
import 'package:ditonton/domain/usecases/get_top_rated_movies.dart' as _i4;
import 'package:ditonton/domain/usecases/get_top_rated_tvs.dart' as _i8;
import 'package:ditonton/domain/usecases/get_watchlist_movies.dart' as _i9;
import 'package:ditonton/domain/usecases/get_watchlist_tvs.dart' as _i10;
import 'package:ditonton/presentation/provider/movie_list_notifier.dart'
    as _i11;
import 'package:ditonton/presentation/provider/tv_list_notifier.dart' as _i17;
import 'package:ditonton/presentation/provider/watchlist_movie_notifier.dart'
    as _i19;
import 'package:ditonton/presentation/provider/watchlist_tv_notifier.dart'
    as _i20;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetNowPlayingMovies_0 extends _i1.SmartFake
    implements _i2.GetNowPlayingMovies {
  _FakeGetNowPlayingMovies_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularMovies_1 extends _i1.SmartFake
    implements _i3.GetPopularMovies {
  _FakeGetPopularMovies_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedMovies_2 extends _i1.SmartFake
    implements _i4.GetTopRatedMovies {
  _FakeGetTopRatedMovies_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAiringTodayTVs_3 extends _i1.SmartFake
    implements _i5.GetAiringTodayTVs {
  _FakeGetAiringTodayTVs_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetOnTheAirTVs_4 extends _i1.SmartFake
    implements _i6.GetOnTheAirTVs {
  _FakeGetOnTheAirTVs_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularTVs_5 extends _i1.SmartFake implements _i7.GetPopularTVs {
  _FakeGetPopularTVs_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedTVs_6 extends _i1.SmartFake
    implements _i8.GetTopRatedTVs {
  _FakeGetTopRatedTVs_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchlistMovies_7 extends _i1.SmartFake
    implements _i9.GetWatchlistMovies {
  _FakeGetWatchlistMovies_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchlistTVs_8 extends _i1.SmartFake
    implements _i10.GetWatchlistTVs {
  _FakeGetWatchlistTVs_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieListNotifier extends _i1.Mock implements _i11.MovieListNotifier {
  MockMovieListNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i12.Movie> get nowPlayingMovies => (super.noSuchMethod(
    Invocation.getter(#nowPlayingMovies),
    returnValue: <_i12.Movie>[],
  ) as List<_i12.Movie>);

  @override
  _i13.RequestState get nowPlayingState => (super.noSuchMethod(
    Invocation.getter(#nowPlayingState),
    returnValue: _i13.RequestState.empty,
  ) as _i13.RequestState);

  @override
  List<_i12.Movie> get popularMovies => (super.noSuchMethod(
    Invocation.getter(#popularMovies),
    returnValue: <_i12.Movie>[],
  ) as List<_i12.Movie>);

  @override
  _i13.RequestState get popularMoviesState => (super.noSuchMethod(
    Invocation.getter(#popularMoviesState),
    returnValue: _i13.RequestState.empty,
  ) as _i13.RequestState);

  @override
  List<_i12.Movie> get topRatedMovies => (super.noSuchMethod(
    Invocation.getter(#topRatedMovies),
    returnValue: <_i12.Movie>[],
  ) as List<_i12.Movie>);

  @override
  _i13.RequestState get topRatedMoviesState => (super.noSuchMethod(
    Invocation.getter(#topRatedMoviesState),
    returnValue: _i13.RequestState.empty,
  ) as _i13.RequestState);

  @override
  String get message => (super.noSuchMethod(
    Invocation.getter(#message),
    returnValue: _i14.dummyValue<String>(this, Invocation.getter(#message)),
  ) as String);

  @override
  _i2.GetNowPlayingMovies get getNowPlayingMovies => (super.noSuchMethod(
    Invocation.getter(#getNowPlayingMovies),
    returnValue: _FakeGetNowPlayingMovies_0(
      this,
      Invocation.getter(#getNowPlayingMovies),
    ),
  ) as _i2.GetNowPlayingMovies);

  @override
  _i3.GetPopularMovies get getPopularMovies => (super.noSuchMethod(
    Invocation.getter(#getPopularMovies),
    returnValue: _FakeGetPopularMovies_1(
      this,
      Invocation.getter(#getPopularMovies),
    ),
  ) as _i3.GetPopularMovies);

  @override
  _i4.GetTopRatedMovies get getTopRatedMovies => (super.noSuchMethod(
    Invocation.getter(#getTopRatedMovies),
    returnValue: _FakeGetTopRatedMovies_2(
      this,
      Invocation.getter(#getTopRatedMovies),
    ),
  ) as _i4.GetTopRatedMovies);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i15.Future<void> fetchNowPlayingMovies() => (super.noSuchMethod(
    Invocation.method(#fetchNowPlayingMovies, []),
    returnValue: _i15.Future<void>.value(),
    returnValueForMissingStub: _i15.Future<void>.value(),
  ) as _i15.Future<void>);

  @override
  _i15.Future<void> fetchPopularMovies() => (super.noSuchMethod(
    Invocation.method(#fetchPopularMovies, []),
    returnValue: _i15.Future<void>.value(),
    returnValueForMissingStub: _i15.Future<void>.value(),
  ) as _i15.Future<void>);

  @override
  _i15.Future<void> fetchTopRatedMovies() => (super.noSuchMethod(
    Invocation.method(#fetchTopRatedMovies, []),
    returnValue: _i15.Future<void>.value(),
    returnValueForMissingStub: _i15.Future<void>.value(),
  ) as _i15.Future<void>);

  @override
  void addListener(_i16.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i16.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TVListNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVListNotifier extends _i1.Mock implements _i17.TVListNotifier {
  MockTVListNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i18.TV> get airingTodayTvs => (super.noSuchMethod(
    Invocation.getter(#airingTodayTvs),
    returnValue: <_i18.TV>[],
  ) as List<_i18.TV>);

  @override
  _i13.RequestState get airingTodayState => (super.noSuchMethod(
    Invocation.getter(#airingTodayState),
    returnValue: _i13.RequestState.empty,
  ) as _i13.RequestState);

  @override
  List<_i18.TV> get onTheAirTvs => (super.noSuchMethod(
    Invocation.getter(#onTheAirTvs),
    returnValue: <_i18.TV>[],
  ) as List<_i18.TV>);

  @override
  _i13.RequestState get onTheAirState => (super.noSuchMethod(
    Invocation.getter(#onTheAirState),
    returnValue: _i13.RequestState.empty,
  ) as _i13.RequestState);

  @override
  List<_i18.TV> get popularTvs => (super.noSuchMethod(
    Invocation.getter(#popularTvs),
    returnValue: <_i18.TV>[],
  ) as List<_i18.TV>);

  @override
  _i13.RequestState get popularTvsState => (super.noSuchMethod(
    Invocation.getter(#popularTvsState),
    returnValue: _i13.RequestState.empty,
  ) as _i13.RequestState);

  @override
  List<_i18.TV> get topRatedTvs => (super.noSuchMethod(
    Invocation.getter(#topRatedTvs),
    returnValue: <_i18.TV>[],
  ) as List<_i18.TV>);

  @override
  _i13.RequestState get topRatedTvsState => (super.noSuchMethod(
    Invocation.getter(#topRatedTvsState),
    returnValue: _i13.RequestState.empty,
  ) as _i13.RequestState);

  @override
  String get message => (super.noSuchMethod(
    Invocation.getter(#message),
    returnValue: _i14.dummyValue<String>(this, Invocation.getter(#message)),
  ) as String);

  @override
  _i5.GetAiringTodayTVs get getAiringTodayTvs => (super.noSuchMethod(
    Invocation.getter(#getAiringTodayTvs),
    returnValue: _FakeGetAiringTodayTVs_3(
      this,
      Invocation.getter(#getAiringTodayTvs),
    ),
  ) as _i5.GetAiringTodayTVs);

  @override
  _i6.GetOnTheAirTVs get getOnTheAirTvs => (super.noSuchMethod(
    Invocation.getter(#getOnTheAirTvs),
    returnValue: _FakeGetOnTheAirTVs_4(
      this,
      Invocation.getter(#getOnTheAirTvs),
    ),
  ) as _i6.GetOnTheAirTVs);

  @override
  _i7.GetPopularTVs get getPopularTvs => (super.noSuchMethod(
    Invocation.getter(#getPopularTvs),
    returnValue: _FakeGetPopularTVs_5(this, Invocation.getter(#getPopularTvs)),
  ) as _i7.GetPopularTVs);

  @override
  _i8.GetTopRatedTVs get getTopRatedTvs => (super.noSuchMethod(
    Invocation.getter(#getTopRatedTvs),
    returnValue: _FakeGetTopRatedTVs_6(
      this,
      Invocation.getter(#getTopRatedTvs),
    ),
  ) as _i8.GetTopRatedTVs);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i15.Future<void> fetchAiringTodayTvs() => (super.noSuchMethod(
    Invocation.method(#fetchAiringTodayTvs, []),
    returnValue: _i15.Future<void>.value(),
    returnValueForMissingStub: _i15.Future<void>.value(),
  ) as _i15.Future<void>);

  @override
  _i15.Future<void> fetchOnTheAirTvs() => (super.noSuchMethod(
    Invocation.method(#fetchOnTheAirTvs, []),
    returnValue: _i15.Future<void>.value(),
    returnValueForMissingStub: _i15.Future<void>.value(),
  ) as _i15.Future<void>);

  @override
  _i15.Future<void> fetchPopularTvs() => (super.noSuchMethod(
    Invocation.method(#fetchPopularTvs, []),
    returnValue: _i15.Future<void>.value(),
    returnValueForMissingStub: _i15.Future<void>.value(),
  ) as _i15.Future<void>);

  @override
  _i15.Future<void> fetchTopRatedTvs() => (super.noSuchMethod(
    Invocation.method(#fetchTopRatedTvs, []),
    returnValue: _i15.Future<void>.value(),
    returnValueForMissingStub: _i15.Future<void>.value(),
  ) as _i15.Future<void>);

  @override
  void addListener(_i16.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i16.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WatchlistMovieNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistMovieNotifier extends _i1.Mock
    implements _i19.WatchlistMovieNotifier {
  MockWatchlistMovieNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i12.Movie> get watchlistMovies => (super.noSuchMethod(
    Invocation.getter(#watchlistMovies),
    returnValue: <_i12.Movie>[],
  ) as List<_i12.Movie>);

  @override
  _i13.RequestState get watchlistState => (super.noSuchMethod(
    Invocation.getter(#watchlistState),
    returnValue: _i13.RequestState.empty,
  ) as _i13.RequestState);

  @override
  String get message => (super.noSuchMethod(
    Invocation.getter(#message),
    returnValue: _i14.dummyValue<String>(this, Invocation.getter(#message)),
  ) as String);

  @override
  _i9.GetWatchlistMovies get getWatchlistMovies => (super.noSuchMethod(
    Invocation.getter(#getWatchlistMovies),
    returnValue: _FakeGetWatchlistMovies_7(
      this,
      Invocation.getter(#getWatchlistMovies),
    ),
  ) as _i9.GetWatchlistMovies);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i15.Future<void> fetchWatchlistMovies() => (super.noSuchMethod(
    Invocation.method(#fetchWatchlistMovies, []),
    returnValue: _i15.Future<void>.value(),
    returnValueForMissingStub: _i15.Future<void>.value(),
  ) as _i15.Future<void>);

  @override
  void addListener(_i16.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i16.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [WatchlistTVNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistTVNotifier extends _i1.Mock
    implements _i20.WatchlistTVNotifier {
  MockWatchlistTVNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i18.TV> get watchlistTvs => (super.noSuchMethod(
    Invocation.getter(#watchlistTvs),
    returnValue: <_i18.TV>[],
  ) as List<_i18.TV>);

  @override
  _i13.RequestState get watchlistState => (super.noSuchMethod(
    Invocation.getter(#watchlistState),
    returnValue: _i13.RequestState.empty,
  ) as _i13.RequestState);

  @override
  String get message => (super.noSuchMethod(
    Invocation.getter(#message),
    returnValue: _i14.dummyValue<String>(this, Invocation.getter(#message)),
  ) as String);

  @override
  _i10.GetWatchlistTVs get getWatchlistTvs => (super.noSuchMethod(
    Invocation.getter(#getWatchlistTvs),
    returnValue: _FakeGetWatchlistTVs_8(
      this,
      Invocation.getter(#getWatchlistTvs),
    ),
  ) as _i10.GetWatchlistTVs);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i15.Future<void> fetchWatchlistTvs() => (super.noSuchMethod(
    Invocation.method(#fetchWatchlistTvs, []),
    returnValue: _i15.Future<void>.value(),
    returnValueForMissingStub: _i15.Future<void>.value(),
  ) as _i15.Future<void>);

  @override
  void addListener(_i16.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i16.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
