// Mocks generated by Mockito from annotations
// in ditonton/test/presentation/pages/list_pages_nonempty_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i12;
import 'dart:ui' as _i13;

import 'package:ditonton/common/state_enum.dart' as _i9;
import 'package:ditonton/domain/entities/movie.dart' as _i10;
import 'package:ditonton/domain/entities/tv.dart' as _i16;
import 'package:ditonton/domain/usecases/get_airing_today_tvs.dart' as _i6;
import 'package:ditonton/domain/usecases/get_on_the_air_tvs.dart' as _i7;
import 'package:ditonton/domain/usecases/get_popular_movies.dart' as _i2;
import 'package:ditonton/domain/usecases/get_popular_tvs.dart' as _i4;
import 'package:ditonton/domain/usecases/get_top_rated_movies.dart' as _i3;
import 'package:ditonton/domain/usecases/get_top_rated_tvs.dart' as _i5;
import 'package:ditonton/presentation/provider/airing_today_tvs_notifier.dart'
    as _i18;
import 'package:ditonton/presentation/provider/on_the_air_tvs_notifier.dart'
    as _i19;
import 'package:ditonton/presentation/provider/popular_movies_notifier.dart'
    as _i8;
import 'package:ditonton/presentation/provider/popular_tvs_notifier.dart'
    as _i15;
import 'package:ditonton/presentation/provider/top_rated_movies_notifier.dart'
    as _i14;
import 'package:ditonton/presentation/provider/top_rated_tvs_notifier.dart'
    as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetPopularMovies_0 extends _i1.SmartFake
    implements _i2.GetPopularMovies {
  _FakeGetPopularMovies_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedMovies_1 extends _i1.SmartFake
    implements _i3.GetTopRatedMovies {
  _FakeGetTopRatedMovies_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularTVs_2 extends _i1.SmartFake implements _i4.GetPopularTVs {
  _FakeGetPopularTVs_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedTVs_3 extends _i1.SmartFake
    implements _i5.GetTopRatedTVs {
  _FakeGetTopRatedTVs_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAiringTodayTVs_4 extends _i1.SmartFake
    implements _i6.GetAiringTodayTVs {
  _FakeGetAiringTodayTVs_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetOnTheAirTVs_5 extends _i1.SmartFake
    implements _i7.GetOnTheAirTVs {
  _FakeGetOnTheAirTVs_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PopularMoviesNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularMoviesNotifier extends _i1.Mock
    implements _i8.PopularMoviesNotifier {
  MockPopularMoviesNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetPopularMovies get getPopularMovies => (super.noSuchMethod(
    Invocation.getter(#getPopularMovies),
    returnValue: _FakeGetPopularMovies_0(
      this,
      Invocation.getter(#getPopularMovies),
    ),
  ) as _i2.GetPopularMovies);

  @override
  _i9.RequestState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _i9.RequestState.empty,
  ) as _i9.RequestState);

  @override
  List<_i10.Movie> get movies => (super.noSuchMethod(
    Invocation.getter(#movies),
    returnValue: <_i10.Movie>[],
  ) as List<_i10.Movie>);

  @override
  String get message => (super.noSuchMethod(
    Invocation.getter(#message),
    returnValue: _i11.dummyValue<String>(this, Invocation.getter(#message)),
  ) as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i12.Future<void> fetchPopularMovies() => (super.noSuchMethod(
    Invocation.method(#fetchPopularMovies, []),
    returnValue: _i12.Future<void>.value(),
    returnValueForMissingStub: _i12.Future<void>.value(),
  ) as _i12.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TopRatedMoviesNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedMoviesNotifier extends _i1.Mock
    implements _i14.TopRatedMoviesNotifier {
  MockTopRatedMoviesNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetTopRatedMovies get getTopRatedMovies => (super.noSuchMethod(
    Invocation.getter(#getTopRatedMovies),
    returnValue: _FakeGetTopRatedMovies_1(
      this,
      Invocation.getter(#getTopRatedMovies),
    ),
  ) as _i3.GetTopRatedMovies);

  @override
  _i9.RequestState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _i9.RequestState.empty,
  ) as _i9.RequestState);

  @override
  List<_i10.Movie> get movies => (super.noSuchMethod(
    Invocation.getter(#movies),
    returnValue: <_i10.Movie>[],
  ) as List<_i10.Movie>);

  @override
  String get message => (super.noSuchMethod(
    Invocation.getter(#message),
    returnValue: _i11.dummyValue<String>(this, Invocation.getter(#message)),
  ) as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i12.Future<void> fetchTopRatedMovies() => (super.noSuchMethod(
    Invocation.method(#fetchTopRatedMovies, []),
    returnValue: _i12.Future<void>.value(),
    returnValueForMissingStub: _i12.Future<void>.value(),
  ) as _i12.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PopularTVsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularTVsNotifier extends _i1.Mock
    implements _i15.PopularTVsNotifier {
  MockPopularTVsNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GetPopularTVs get getPopularTvs => (super.noSuchMethod(
    Invocation.getter(#getPopularTvs),
    returnValue: _FakeGetPopularTVs_2(this, Invocation.getter(#getPopularTvs)),
  ) as _i4.GetPopularTVs);

  @override
  _i9.RequestState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _i9.RequestState.empty,
  ) as _i9.RequestState);

  @override
  List<_i16.TV> get tvs =>
      (super.noSuchMethod(Invocation.getter(#tvs), returnValue: <_i16.TV>[])
          as List<_i16.TV>);

  @override
  String get message => (super.noSuchMethod(
    Invocation.getter(#message),
    returnValue: _i11.dummyValue<String>(this, Invocation.getter(#message)),
  ) as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i12.Future<void> fetchPopularTvs() => (super.noSuchMethod(
    Invocation.method(#fetchPopularTvs, []),
    returnValue: _i12.Future<void>.value(),
    returnValueForMissingStub: _i12.Future<void>.value(),
  ) as _i12.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TopRatedTVsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTVsNotifier extends _i1.Mock
    implements _i17.TopRatedTVsNotifier {
  MockTopRatedTVsNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.GetTopRatedTVs get getTopRatedTvs => (super.noSuchMethod(
    Invocation.getter(#getTopRatedTvs),
    returnValue: _FakeGetTopRatedTVs_3(
      this,
      Invocation.getter(#getTopRatedTvs),
    ),
  ) as _i5.GetTopRatedTVs);

  @override
  _i9.RequestState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _i9.RequestState.empty,
  ) as _i9.RequestState);

  @override
  List<_i16.TV> get tvs =>
      (super.noSuchMethod(Invocation.getter(#tvs), returnValue: <_i16.TV>[])
          as List<_i16.TV>);

  @override
  String get message => (super.noSuchMethod(
    Invocation.getter(#message),
    returnValue: _i11.dummyValue<String>(this, Invocation.getter(#message)),
  ) as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i12.Future<void> fetchTopRatedTvs() => (super.noSuchMethod(
    Invocation.method(#fetchTopRatedTvs, []),
    returnValue: _i12.Future<void>.value(),
    returnValueForMissingStub: _i12.Future<void>.value(),
  ) as _i12.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AiringTodayTVsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiringTodayTVsNotifier extends _i1.Mock
    implements _i18.AiringTodayTVsNotifier {
  MockAiringTodayTVsNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.GetAiringTodayTVs get getAiringTodayTvs => (super.noSuchMethod(
    Invocation.getter(#getAiringTodayTvs),
    returnValue: _FakeGetAiringTodayTVs_4(
      this,
      Invocation.getter(#getAiringTodayTvs),
    ),
  ) as _i6.GetAiringTodayTVs);

  @override
  _i9.RequestState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _i9.RequestState.empty,
  ) as _i9.RequestState);

  @override
  List<_i16.TV> get tvs =>
      (super.noSuchMethod(Invocation.getter(#tvs), returnValue: <_i16.TV>[])
          as List<_i16.TV>);

  @override
  String get message => (super.noSuchMethod(
    Invocation.getter(#message),
    returnValue: _i11.dummyValue<String>(this, Invocation.getter(#message)),
  ) as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i12.Future<void> fetchAiringTodayTvs() => (super.noSuchMethod(
    Invocation.method(#fetchAiringTodayTvs, []),
    returnValue: _i12.Future<void>.value(),
    returnValueForMissingStub: _i12.Future<void>.value(),
  ) as _i12.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OnTheAirTVsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnTheAirTVsNotifier extends _i1.Mock
    implements _i19.OnTheAirTVsNotifier {
  MockOnTheAirTVsNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.GetOnTheAirTVs get getOnTheAirTvs => (super.noSuchMethod(
    Invocation.getter(#getOnTheAirTvs),
    returnValue: _FakeGetOnTheAirTVs_5(
      this,
      Invocation.getter(#getOnTheAirTvs),
    ),
  ) as _i7.GetOnTheAirTVs);

  @override
  _i9.RequestState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _i9.RequestState.empty,
  ) as _i9.RequestState);

  @override
  List<_i16.TV> get tvs =>
      (super.noSuchMethod(Invocation.getter(#tvs), returnValue: <_i16.TV>[])
          as List<_i16.TV>);

  @override
  String get message => (super.noSuchMethod(
    Invocation.getter(#message),
    returnValue: _i11.dummyValue<String>(this, Invocation.getter(#message)),
  ) as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i12.Future<void> fetchOnTheAirTvs() => (super.noSuchMethod(
    Invocation.method(#fetchOnTheAirTvs, []),
    returnValue: _i12.Future<void>.value(),
    returnValueForMissingStub: _i12.Future<void>.value(),
  ) as _i12.Future<void>);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
