// Mocks generated by Mockito from annotations
// in ditonton/test/presentation/pages/search_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i8;
import 'dart:ui' as _i9;

import 'package:ditonton/common/state_enum.dart' as _i5;
import 'package:ditonton/domain/entities/movie.dart' as _i6;
import 'package:ditonton/domain/entities/tv.dart' as _i11;
import 'package:ditonton/domain/usecases/search_movies.dart' as _i2;
import 'package:ditonton/domain/usecases/search_tvs.dart' as _i3;
import 'package:ditonton/presentation/provider/movie_search_notifier.dart'
    as _i4;
import 'package:ditonton/presentation/provider/tv_search_notifier.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSearchMovies_0 extends _i1.SmartFake implements _i2.SearchMovies {
  _FakeSearchMovies_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchTVs_1 extends _i1.SmartFake implements _i3.SearchTVs {
  _FakeSearchTVs_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieSearchNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieSearchNotifier extends _i1.Mock
    implements _i4.MovieSearchNotifier {
  MockMovieSearchNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SearchMovies get searchMovies => (super.noSuchMethod(
    Invocation.getter(#searchMovies),
    returnValue: _FakeSearchMovies_0(this, Invocation.getter(#searchMovies)),
  ) as _i2.SearchMovies);

  @override
  _i5.RequestState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _i5.RequestState.empty,
  ) as _i5.RequestState);

  @override
  List<_i6.Movie> get searchResult => (super.noSuchMethod(
    Invocation.getter(#searchResult),
    returnValue: <_i6.Movie>[],
  ) as List<_i6.Movie>);

  @override
  String get message => (super.noSuchMethod(
    Invocation.getter(#message),
    returnValue: _i7.dummyValue<String>(this, Invocation.getter(#message)),
  ) as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> fetchMovieSearch(String? query) => (super.noSuchMethod(
    Invocation.method(#fetchMovieSearch, [query]),
    returnValue: _i8.Future<void>.value(),
    returnValueForMissingStub: _i8.Future<void>.value(),
  ) as _i8.Future<void>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TVSearchNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSearchNotifier extends _i1.Mock implements _i10.TVSearchNotifier {
  MockTVSearchNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.SearchTVs get searchTvs => (super.noSuchMethod(
    Invocation.getter(#searchTvs),
    returnValue: _FakeSearchTVs_1(this, Invocation.getter(#searchTvs)),
  ) as _i3.SearchTVs);

  @override
  _i5.RequestState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _i5.RequestState.empty,
  ) as _i5.RequestState);

  @override
  List<_i11.TV> get searchResult => (super.noSuchMethod(
    Invocation.getter(#searchResult),
    returnValue: <_i11.TV>[],
  ) as List<_i11.TV>);

  @override
  String get message => (super.noSuchMethod(
    Invocation.getter(#message),
    returnValue: _i7.dummyValue<String>(this, Invocation.getter(#message)),
  ) as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> fetchTvSearch(String? query) => (super.noSuchMethod(
    Invocation.method(#fetchTvSearch, [query]),
    returnValue: _i8.Future<void>.value(),
    returnValueForMissingStub: _i8.Future<void>.value(),
  ) as _i8.Future<void>);

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
