// Mocks generated by Mockito from annotations
// in ditonton/test/presentation/pages/tv_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i13;
import 'dart:ui' as _i14;

import 'package:ditonton/common/state_enum.dart' as _i10;
import 'package:ditonton/domain/entities/tv.dart' as _i11;
import 'package:ditonton/domain/entities/tv_detail.dart' as _i8;
import 'package:ditonton/domain/usecases/get_season_detail.dart' as _i4;
import 'package:ditonton/domain/usecases/get_tv_detail.dart' as _i2;
import 'package:ditonton/domain/usecases/get_tv_recommendations.dart' as _i3;
import 'package:ditonton/domain/usecases/get_watchlist_tv_status.dart' as _i5;
import 'package:ditonton/domain/usecases/remove_watchlist_tv.dart' as _i7;
import 'package:ditonton/domain/usecases/save_watchlist_tv.dart' as _i6;
import 'package:ditonton/presentation/provider/tv_detail_notifier.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetTVDetail_0 extends _i1.SmartFake implements _i2.GetTVDetail {
  _FakeGetTVDetail_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTVRecommendations_1 extends _i1.SmartFake
    implements _i3.GetTVRecommendations {
  _FakeGetTVRecommendations_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetSeasonDetail_2 extends _i1.SmartFake
    implements _i4.GetSeasonDetail {
  _FakeGetSeasonDetail_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchlistTVStatus_3 extends _i1.SmartFake
    implements _i5.GetWatchlistTVStatus {
  _FakeGetWatchlistTVStatus_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlistTV_4 extends _i1.SmartFake
    implements _i6.SaveWatchlistTV {
  _FakeSaveWatchlistTV_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlistTV_5 extends _i1.SmartFake
    implements _i7.RemoveWatchlistTV {
  _FakeRemoveWatchlistTV_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTVDetail_6 extends _i1.SmartFake implements _i8.TVDetail {
  _FakeTVDetail_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TVDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVDetailNotifier extends _i1.Mock implements _i9.TVDetailNotifier {
  MockTVDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTVDetail get getTvDetail => (super.noSuchMethod(
    Invocation.getter(#getTvDetail),
    returnValue: _FakeGetTVDetail_0(this, Invocation.getter(#getTvDetail)),
  ) as _i2.GetTVDetail);

  @override
  _i3.GetTVRecommendations get getTvRecommendations => (super.noSuchMethod(
    Invocation.getter(#getTvRecommendations),
    returnValue: _FakeGetTVRecommendations_1(
      this,
      Invocation.getter(#getTvRecommendations),
    ),
  ) as _i3.GetTVRecommendations);

  @override
  _i4.GetSeasonDetail get getSeasonDetail => (super.noSuchMethod(
    Invocation.getter(#getSeasonDetail),
    returnValue: _FakeGetSeasonDetail_2(
      this,
      Invocation.getter(#getSeasonDetail),
    ),
  ) as _i4.GetSeasonDetail);

  @override
  _i5.GetWatchlistTVStatus get getWatchlistTvStatus => (super.noSuchMethod(
    Invocation.getter(#getWatchlistTvStatus),
    returnValue: _FakeGetWatchlistTVStatus_3(
      this,
      Invocation.getter(#getWatchlistTvStatus),
    ),
  ) as _i5.GetWatchlistTVStatus);

  @override
  _i6.SaveWatchlistTV get saveWatchlistTv => (super.noSuchMethod(
    Invocation.getter(#saveWatchlistTv),
    returnValue: _FakeSaveWatchlistTV_4(
      this,
      Invocation.getter(#saveWatchlistTv),
    ),
  ) as _i6.SaveWatchlistTV);

  @override
  _i7.RemoveWatchlistTV get removeWatchlistTv => (super.noSuchMethod(
    Invocation.getter(#removeWatchlistTv),
    returnValue: _FakeRemoveWatchlistTV_5(
      this,
      Invocation.getter(#removeWatchlistTv),
    ),
  ) as _i7.RemoveWatchlistTV);

  @override
  _i8.TVDetail get tv => (super.noSuchMethod(
    Invocation.getter(#tv),
    returnValue: _FakeTVDetail_6(this, Invocation.getter(#tv)),
  ) as _i8.TVDetail);

  @override
  _i10.RequestState get tvState => (super.noSuchMethod(
    Invocation.getter(#tvState),
    returnValue: _i10.RequestState.empty,
  ) as _i10.RequestState);

  @override
  List<_i11.TV> get tvRecommendations => (super.noSuchMethod(
    Invocation.getter(#tvRecommendations),
    returnValue: <_i11.TV>[],
  ) as List<_i11.TV>);

  @override
  _i10.RequestState get recommendationState => (super.noSuchMethod(
    Invocation.getter(#recommendationState),
    returnValue: _i10.RequestState.empty,
  ) as _i10.RequestState);

  @override
  _i10.RequestState get seasonDetailState => (super.noSuchMethod(
    Invocation.getter(#seasonDetailState),
    returnValue: _i10.RequestState.empty,
  ) as _i10.RequestState);

  @override
  String get message => (super.noSuchMethod(
    Invocation.getter(#message),
    returnValue: _i12.dummyValue<String>(this, Invocation.getter(#message)),
  ) as String);

  @override
  bool get isAddedToWatchlist => (super.noSuchMethod(
    Invocation.getter(#isAddedToWatchlist),
    returnValue: false,
  ) as bool);

  @override
  String get watchlistMessage => (super.noSuchMethod(
    Invocation.getter(#watchlistMessage),
    returnValue: _i12.dummyValue<String>(
      this,
      Invocation.getter(#watchlistMessage),
    ),
  ) as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i13.Future<void> fetchTvDetail(int? id) => (super.noSuchMethod(
    Invocation.method(#fetchTvDetail, [id]),
    returnValue: _i13.Future<void>.value(),
    returnValueForMissingStub: _i13.Future<void>.value(),
  ) as _i13.Future<void>);

  @override
  _i13.Future<void> fetchSeasonDetail(int? id, int? seasonNumber) =>
      (super.noSuchMethod(
        Invocation.method(#fetchSeasonDetail, [id, seasonNumber]),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> addWatchlist(_i8.TVDetail? tv) => (super.noSuchMethod(
    Invocation.method(#addWatchlist, [tv]),
    returnValue: _i13.Future<void>.value(),
    returnValueForMissingStub: _i13.Future<void>.value(),
  ) as _i13.Future<void>);

  @override
  _i13.Future<void> removeFromWatchlist(_i8.TVDetail? tv) =>
      (super.noSuchMethod(
        Invocation.method(#removeFromWatchlist, [tv]),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);

  @override
  _i13.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
    Invocation.method(#loadWatchlistStatus, [id]),
    returnValue: _i13.Future<void>.value(),
    returnValueForMissingStub: _i13.Future<void>.value(),
  ) as _i13.Future<void>);

  @override
  void addListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
