// Mocks generated by Mockito from annotations
// in ditonton/test/presentation/pages/tv_pages_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i10;
import 'dart:ui' as _i11;

import 'package:ditonton/common/state_enum.dart' as _i7;
import 'package:ditonton/domain/entities/tv.dart' as _i8;
import 'package:ditonton/domain/usecases/get_airing_today_tvs.dart' as _i4;
import 'package:ditonton/domain/usecases/get_on_the_air_tvs.dart' as _i5;
import 'package:ditonton/domain/usecases/get_popular_tvs.dart' as _i2;
import 'package:ditonton/domain/usecases/get_top_rated_tvs.dart' as _i3;
import 'package:ditonton/presentation/provider/airing_today_tvs_notifier.dart'
    as _i13;
import 'package:ditonton/presentation/provider/on_the_air_tvs_notifier.dart'
    as _i14;
import 'package:ditonton/presentation/provider/popular_tvs_notifier.dart'
    as _i6;
import 'package:ditonton/presentation/provider/top_rated_tvs_notifier.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetPopularTVs_0 extends _i1.SmartFake implements _i2.GetPopularTVs {
  _FakeGetPopularTVs_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedTVs_1 extends _i1.SmartFake
    implements _i3.GetTopRatedTVs {
  _FakeGetTopRatedTVs_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAiringTodayTVs_2 extends _i1.SmartFake
    implements _i4.GetAiringTodayTVs {
  _FakeGetAiringTodayTVs_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetOnTheAirTVs_3 extends _i1.SmartFake
    implements _i5.GetOnTheAirTVs {
  _FakeGetOnTheAirTVs_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PopularTVsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockPopularTVsNotifier extends _i1.Mock
    implements _i6.PopularTVsNotifier {
  MockPopularTVsNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetPopularTVs get getPopularTvs => (super.noSuchMethod(
    Invocation.getter(#getPopularTvs),
    returnValue: _FakeGetPopularTVs_0(this, Invocation.getter(#getPopularTvs)),
  ) as _i2.GetPopularTVs);

  @override
  _i7.RequestState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _i7.RequestState.empty,
  ) as _i7.RequestState);

  @override
  List<_i8.TV> get tvs =>
      (super.noSuchMethod(Invocation.getter(#tvs), returnValue: <_i8.TV>[])
          as List<_i8.TV>);

  @override
  String get message => (super.noSuchMethod(
    Invocation.getter(#message),
    returnValue: _i9.dummyValue<String>(this, Invocation.getter(#message)),
  ) as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i10.Future<void> fetchPopularTvs() => (super.noSuchMethod(
    Invocation.method(#fetchPopularTvs, []),
    returnValue: _i10.Future<void>.value(),
    returnValueForMissingStub: _i10.Future<void>.value(),
  ) as _i10.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TopRatedTVsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedTVsNotifier extends _i1.Mock
    implements _i12.TopRatedTVsNotifier {
  MockTopRatedTVsNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GetTopRatedTVs get getTopRatedTvs => (super.noSuchMethod(
    Invocation.getter(#getTopRatedTvs),
    returnValue: _FakeGetTopRatedTVs_1(
      this,
      Invocation.getter(#getTopRatedTvs),
    ),
  ) as _i3.GetTopRatedTVs);

  @override
  _i7.RequestState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _i7.RequestState.empty,
  ) as _i7.RequestState);

  @override
  List<_i8.TV> get tvs =>
      (super.noSuchMethod(Invocation.getter(#tvs), returnValue: <_i8.TV>[])
          as List<_i8.TV>);

  @override
  String get message => (super.noSuchMethod(
    Invocation.getter(#message),
    returnValue: _i9.dummyValue<String>(this, Invocation.getter(#message)),
  ) as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i10.Future<void> fetchTopRatedTvs() => (super.noSuchMethod(
    Invocation.method(#fetchTopRatedTvs, []),
    returnValue: _i10.Future<void>.value(),
    returnValueForMissingStub: _i10.Future<void>.value(),
  ) as _i10.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AiringTodayTVsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiringTodayTVsNotifier extends _i1.Mock
    implements _i13.AiringTodayTVsNotifier {
  MockAiringTodayTVsNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.GetAiringTodayTVs get getAiringTodayTvs => (super.noSuchMethod(
    Invocation.getter(#getAiringTodayTvs),
    returnValue: _FakeGetAiringTodayTVs_2(
      this,
      Invocation.getter(#getAiringTodayTvs),
    ),
  ) as _i4.GetAiringTodayTVs);

  @override
  _i7.RequestState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _i7.RequestState.empty,
  ) as _i7.RequestState);

  @override
  List<_i8.TV> get tvs =>
      (super.noSuchMethod(Invocation.getter(#tvs), returnValue: <_i8.TV>[])
          as List<_i8.TV>);

  @override
  String get message => (super.noSuchMethod(
    Invocation.getter(#message),
    returnValue: _i9.dummyValue<String>(this, Invocation.getter(#message)),
  ) as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i10.Future<void> fetchAiringTodayTvs() => (super.noSuchMethod(
    Invocation.method(#fetchAiringTodayTvs, []),
    returnValue: _i10.Future<void>.value(),
    returnValueForMissingStub: _i10.Future<void>.value(),
  ) as _i10.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OnTheAirTVsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnTheAirTVsNotifier extends _i1.Mock
    implements _i14.OnTheAirTVsNotifier {
  MockOnTheAirTVsNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.GetOnTheAirTVs get getOnTheAirTvs => (super.noSuchMethod(
    Invocation.getter(#getOnTheAirTvs),
    returnValue: _FakeGetOnTheAirTVs_3(
      this,
      Invocation.getter(#getOnTheAirTvs),
    ),
  ) as _i5.GetOnTheAirTVs);

  @override
  _i7.RequestState get state => (super.noSuchMethod(
    Invocation.getter(#state),
    returnValue: _i7.RequestState.empty,
  ) as _i7.RequestState);

  @override
  List<_i8.TV> get tvs =>
      (super.noSuchMethod(Invocation.getter(#tvs), returnValue: <_i8.TV>[])
          as List<_i8.TV>);

  @override
  String get message => (super.noSuchMethod(
    Invocation.getter(#message),
    returnValue: _i9.dummyValue<String>(this, Invocation.getter(#message)),
  ) as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i10.Future<void> fetchOnTheAirTvs() => (super.noSuchMethod(
    Invocation.method(#fetchOnTheAirTvs, []),
    returnValue: _i10.Future<void>.value(),
    returnValueForMissingStub: _i10.Future<void>.value(),
  ) as _i10.Future<void>);

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
